### ISSUE TITLE
department task list

### ISSUE THREAD

**Issue by Tanjinhossain1** [Tanjinhossain1/course-management-auth-service#18]
- [ ] ceate a new academic department
- [ ] get all academic department
- [ ] with pagination and search term
- [ ] updateone  academic department
- [ ] delete one academic department
- [ ] find by one academic department
- [ ] error handaling academic department
